<a href="https://colab.research.google.com/github/Byeonjinha/Colab/blob/main/2_Numpy_%EC%8B%A4%EC%8A%B5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
"""
날짜 : 2021/10/18
이름 : 변진하
내용 : Hello Colab 실습하기


Numpy 라이브러리
- 고성능의 수치게산을 위한 파이썬 라이브러리
파이썬의 기본 리스트보다 월등한 연산 성능
행렬이나 대규모 다차원 배열 처리를 지원
"""
import numpy as np
#Numpy 벡터
v1 = np.array([1,2,3,4,5])
print('v1:',v1)

v2 = np.arange(5)
print('v2:', v2)

v3 = np.arange(10)
print('v3:', v3)


v1: [1 2 3 4 5]
v2: [0 1 2 3 4]
v3: [0 1 2 3 4 5 6 7 8 9]


In [ ]:
# 0~1 사이의 임의의 실수 100개
import numpy as np
result1 = np.random.rand(100)
# 표준정규분포를 따라는 실수 100개
result2= np.random.randn(100)
# 0~9 사이의 임의의 정수
result3 = np.random.randint(10)
result1, result2, result3


(array([0.9084468 , 0.60300016, 0.01278244, 0.14284971, 0.18308878,
        0.31234704, 0.88005445, 0.0701522 , 0.93249871, 0.60394537,
        0.27523443, 0.80795302, 0.59281197, 0.28669917, 0.0176307 ,
        0.80450138, 0.65907525, 0.70703078, 0.59546625, 0.69322683,
        0.74421351, 0.57506176, 0.55359766, 0.86313518, 0.13007047,
        0.2730467 , 0.8179134 , 0.52497713, 0.51795354, 0.34256621,
        0.52100501, 0.71917465, 0.4547086 , 0.34615103, 0.4030138 ,
        0.59741186, 0.0263382 , 0.16131899, 0.71495477, 0.73290291,
        0.29960555, 0.16988799, 0.5855085 , 0.90110602, 0.37337347,
        0.67545668, 0.89527716, 0.62989307, 0.0126486 , 0.61745348,
        0.71051389, 0.56169027, 0.03051806, 0.37615482, 0.6313207 ,
        0.56184711, 0.68703868, 0.37089346, 0.70338425, 0.10079705,
        0.60894791, 0.93217619, 0.10095147, 0.62397989, 0.17047303,
        0.92010585, 0.08305351, 0.91027098, 0.59452891, 0.93550616,
        0.91733485, 0.28580166, 0.83284307, 0.44

In [ ]:
#numpy 행렬
import numpy as np


m1 = np.array([[1,2],[3,4]])
print(m1)
m2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(m2)
m3 = np.ones([2,4])
print(m3)
m4 = np.zeros([3,2])
print(m4)

[[1 2]
 [3 4]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [ ]:
#numpy 인덱싱
mat = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

print("mat[0,0]\n",mat[0,0],"\n")
print("mat[0,:]\n",mat[0,:],"\n")
print("mat[:,0]\n",mat[:,0],"\n")
print("mat[0:2,0:2]=n",mat[0:2,0:2],"\n")
print("mat[:,0:2]=n",mat[:,0:2],"\n")
print("mat[:,2:4]=n",mat[:,2:4],"\n")
print("mat[1:3,1:3]\n",mat[1:3,1:3],"\n")


mat[0,0]
 1 

mat[0,:]
 [1 2 3 4] 

mat[:,0]
 [1 5 9] 

mat[0:2,0:2]=n [[1 2]
 [5 6]] 

mat[:,0:2]=n [[ 1  2]
 [ 5  6]
 [ 9 10]] 

mat[:,2:4]=n [[ 3  4]
 [ 7  8]
 [11 12]] 

mat[1:3,1:3]
 [[ 6  7]
 [10 11]] 

